spring:
  application:
    name: application-local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/bomMeong
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    stack:
      auto: false

jwt:
  secret:
    key: ${JWT_KEY}
