spring:
  application:
    name: bommeong-dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${RDS_URL}
    username: root
    password: ${RDS_PWD}
    driver-class-name: org.mariadb.jdbc.Driver

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    stack:
      auto: false



jwt:
  secret:
    key: ${JWT_KEY}

#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: ${KEY_STORE_PASSWORD}
